name: hangout
description: A new Flutter project.


publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

  hexcolor: ^2.0.5
  google_fonts: ^2.1.0
  image_picker: ^0.8.4
  dio: ^4.0.6
  shared_preferences: ^2.0.7
  date_picker_timeline: ^1.2.3
  carousel_slider: ^4.0.0
  smooth_page_indicator: ^1.0.0+2
  cached_network_image: ^3.1.0
  fvm: ^2.2.6
  provider: ^6.0.2
  http_parser: ^4.0.0
  http: ^0.13.4
  flutter_animated_button: ^2.0.0
  path: ^1.8.0
  flutter_launcher_icons: ^0.9.3
  crypto: ^3.0.2
  mongo_dart: ^0.7.4+1
  toast: ^0.3.0
  flutter_native_splash: ^2.0.1+1
  firebase_core: ^1.20.1
  firebase_messaging: ^12.0.2

flutter_native_splash:
   image: assets/images/icon.png
   color: "#000000"


dev_dependencies:
  flutter_test:
    sdk: flutter


flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/icon.png"
  


flutter:

   uses-material-design: true

   assets:
    - assets/images/
    
  