name: hangout
description: A new Flutter project.


publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

  hexcolor: ^2.0.5
  google_fonts: ^2.1.0
  image_picker: ^0.8.4
  dio: ^4.0.6
  shared_preferences: ^2.0.7
  date_picker_timeline: ^1.2.3
  carousel_slider: ^4.0.0
  smooth_page_indicator: ^1.0.0+2
  cached_network_image: ^3.1.0
  fvm: ^2.2.6
  provider: ^6.0.2
  http_parser: ^4.0.0
  http: ^0.13.4
  flutter_animated_button: ^2.0.0
  path: ^1.8.0
  

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:

   uses-material-design: true

   assets:
    - assets/images/
    - assets/icons/

  